<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
name="LOVInq" targetNamespace="http://www.sama.bea.sa/public/LOVInq" 
xmlns:tns ="http://www.sama.bea.sa/public/LOVInq" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema">


	<wsdl:types>
        <xsd:schema targetNamespace="http://www.sama.bea.sa/public/LOVInq">
            <xsd:include schemaLocation="LOVInq.xsd"/>
		</xsd:schema>
    </wsdl:types>

	<wsdl:message name="getLovListRequestMsg">
		<wsdl:part element="tns:getLovList" name="getLovListParameters"/>
	</wsdl:message>
	<wsdl:message name="getLovListResponseMsg">
		<wsdl:part element="tns:getLovListResponse" name="getLovListResult"/>
	</wsdl:message>	

	
	<wsdl:portType name="LOVInq">
        <wsdl:operation name="getLovList">
			<wsdl:input message="tns:getLovListRequestMsg"/>
			<wsdl:output message="tns:getLovListResponseMsg"/>
		</wsdl:operation>
    </wsdl:portType>
	
	 <wsdl:binding name="LOVInqSOAP" type="tns:LOVInq">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getLovList">
			<soap:operation soapAction="http://www.sama.bea.sa/public/LOVInq/getLovList"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
    </wsdl:binding>

	<wsdl:service name="LOVInqService">
		<wsdl:port binding="tns:LOVInqSOAP" name="LOVInqSOAP">
			<soap:address location="http://localhost:7800/LOVInq"/>
		</wsdl:port>
    </wsdl:service>
	
</wsdl:definitions>