<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:uat="http://www.sama.bea.sa/public/services/UploadAttachCallBack"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="UploadAttachCallBack"
    targetNamespace="http://www.sama.bea.sa/public/services/UploadAttachCallBack" xmlns:uatt="http://www.sama.bea.sa/public/services/UploadAttach"
    xmlns:head="http://www.sama.bea.sa/common/Header">

    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sama.bea.sa/public/services/UploadAttach" schemaLocation="UploadAttach.xsd" />
            <xsd:import namespace="http://www.sama.bea.sa/common/Header" schemaLocation="../common/Header.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="UploadAttachCallBackRq">
        <wsdl:part element="uatt:UploadAttachCallBackRq" name="parameters" />
    </wsdl:message>
    <wsdl:message name="UploadAttachCallBackRs">
        <wsdl:part element="uatt:UploadAttachCallBackRs" name="parameters" />
    </wsdl:message>
    <wsdl:message name="RqHdr">
        <wsdl:part element="head:MsgHdrRq" name="header" />
    </wsdl:message>
    <wsdl:message name="RsHdr">
        <wsdl:part element="head:MsgHdrRs" name="header" />
    </wsdl:message>

    <wsdl:portType name="UploadAttachCallBack">
        <wsdl:operation name="UploadAttachCallBack">
            <wsdl:input message="uat:UploadAttachCallBackRq" />
            <wsdl:output message="uat:UploadAttachCallBackRs" />
        </wsdl:operation>
    </wsdl:portType>
    
    <wsdl:binding name="UploadAttachCallBackSOAP" type="uat:UploadAttachCallBack">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="UploadAttachCallBack">
            <soap:operation soapAction="" />
            <wsdl:input>
                <soap:body use="literal" />
                <soap:header message="uat:RqHdr" part="header" use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
                <soap:header message="uat:RsHdr" part="header" use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    
    <wsdl:service name="UploadAttachCallBack">
        <wsdl:port binding="uat:UploadAttachCallBackSOAP" name="UploadAttachCallBackSOAP">
            <soap:address location="http://www.sama.bea.sa/" />
        </wsdl:port>
    </wsdl:service>
    
</wsdl:definitions>